# hestia-goaccess project defaults

GOACCESS_MIN_VERSION=1.10.2
GOACCESS_PORT_RANGE=64000-64999
GOACCESS_LOG_FORMAT=COMBINED
GOACCESS_FILTER_LOG=/usr/local/share/hestia-goaccess/scripts/hestia-goaccess-filter-log
GOACCESS_IGNORE_PATHS=/vstats/
GOACCESS_HTML_PREFS='{"theme":"darkGray"}'
GOACCESS_DB_ROOT=/var/lib/hestia-goaccess
GOACCESS_KEEP_LAST=90
GOACCESS_REALTIME_BIND=127.0.0.1
GOACCESS_REALTIME_WS_PATH=/vstats/ws/
GOACCESS_REALTIME_WS_URL_TEMPLATE=
