# hestia-goaccess static stats marker generated by Hestia.
#
# Hestia renders this file when a domain selects goaccess-static in the
# Web Statistics dropdown. The actual report generation is handled by
# /usr/local/bin/hestia-goaccess through the v-update-web-domain-stat wrapper.

HG_USER='%user%'
HG_DOMAIN='%domain%'
HG_DOMAIN_IDN='%domain_idn%'
HG_MODE='static'
HG_LOG_PATH='/var/log/%web_system%/domains/%domain%.log'
HG_REPORT_PATH='%home%/%user%/web/%domain%/stats/index.html'
