# hestia-goaccess realtime stats marker generated by Hestia.
#
# Hestia renders this file when a domain selects goaccess-realtime in the
# Web Statistics dropdown. The realtime service is created by
# /usr/local/bin/hestia-goaccess through the v-update-web-domain-stat wrapper.

HG_USER='%user%'
HG_DOMAIN='%domain%'
HG_DOMAIN_IDN='%domain_idn%'
HG_MODE='realtime'
HG_LOG_PATH='/var/log/%web_system%/domains/%domain%.log'
HG_REPORT_PATH='%home%/%user%/web/%domain%/stats/index.html'
